# -*- coding: utf-8 -*-
"""healthcredits.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UFVWYMLOx9t9krLTyD687SC6yBb4REld
"""

# --- CELL 1: INSTALLATIONS ---
!apt-get install -y tesseract-ocr
!pip install pytesseract
print("✅ Vision Drivers Installed.")

# --- CELL 2: SETUP & DRIVE MOUNT ---
import pytz
import json, requests, os, cv2, time
import numpy as np
import pytesseract
from datetime import datetime
from google.colab import drive

# 1. AUTH & PATHS
drive.mount('/content/drive')
DATA_FILE = "/content/drive/My Drive/health_credits.json"
TOKEN = "8620321199:AAGzau2p0R8z5u8oM1kLr0d385aPTiWp1dA"
CHAT_ID = "48862354"
TARGET_GOAL = 2500

print("✅ Authentication & Drive Sync Complete.")

# --- CELL 3: LOGIC & CONFIGURATION ---

# YOUR MEDICATION SCHEDULE (Edit these times/names as needed)
MED_SCHEDULE = {
    "06:00": "Gabapentin + Duloxetine + Ketotifen",
    "08:00": "Fludrocortison + Ivabradine + Baclofen + Methylphenidate + Electrolytes",
    "14:00": "Gabapentin + Ketotifen",
    "20:00": "Ivabradine + Levocetirizine + Baclofen",
    "22:00": "Gabapentin + Duloxetine + Ketotifen"
}

def load_data():
    if not os.path.exists(DATA_FILE):
        return {"total_credits": 330, "history": [], "flare_mode": False}
    with open(DATA_FILE, 'r') as f:
        return json.load(f)

def save_data(data):
    with open(DATA_FILE, 'w') as f:
        json.dump(data, f, indent=4)

def send_alert(message):
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={CHAT_ID}&text={message}"
    requests.get(url)

def add_credits(task_name, points):
    data = load_data()
    now_cdmx = datetime.now(pytz.timezone('America/Mexico_City'))
    current_time_str = now_cdmx.strftime("%H:%M")

    # FLARE LOGIC: Double points for survival tasks
    multiplier = 2 if data.get("flare_mode", False) else 1
    final_points = points * multiplier

    # --- GRACE PERIOD LOGIC ---
    # Check if this task is a scheduled med
    for med_time, med_name in MED_SCHEDULE.items():
        if med_name in task_name:
            # Calculate minutes difference
            fmt = "%H:%M"
            d1 = datetime.strptime(current_time_str, fmt)
            d2 = datetime.strptime(med_time, fmt)
            diff_mins = (d1 - d2).total_seconds() / 60

            # If you are more than 15 minutes late, apply a small penalty to the reward
            if 15 < diff_mins <= 30:
                final_points -= 10
                send_alert(f"⚠️ Grace period (5m) exceeded. Penalty applied to reward.")
            elif diff_mins > 30:
                final_points = 0
                send_alert(f"🚫 Window closed (>30m). No points awarded for this dose.")


    data["total_credits"] += final_points
    data["history"].append({
        "timestamp": datetime.now(pytz.timezone('America/Mexico_City')).strftime("%Y-%m-%d %H:%M:%S"),
        "task": task_name,
        "points": final_points
    })

    save_data(data)

    with open(DATA_FILE, 'w') as f:
        json.dump(data, f, indent=4)

    print(f"💾 DRIVE SYNCED: {task_name} (+{final_points} pts). New Total: {data['total_credits']}")
    return data['total_credits']


    # PROGRESS BAR LOGIC
    remaining = TARGET_GOAL - data["total_credits"]
    progress_ratio = data['total_credits'] / TARGET_GOAL
    bar = "▓" * min(int(progress_ratio * 10), 10) + "░" * (10 - min(int(progress_ratio * 10), 10))

    status_icon = "🚨" if data.get("flare_mode") else "✅"
    msg = (f"{status_icon} **Logged:** {task_name}\n"
           f"Earned: {final_points} pts {'(FLARE x2!)' if multiplier == 2 else ''}\n"
           f"Progress: {bar} {round(progress_ratio * 100)}%\n"
           f"Remaining: {max(0, remaining)} pts to Keyboard!")
    send_alert(msg)

def log_penalty(reason, points):
    data = load_data()
    if data.get("flare_mode", False): # No penalties during flares!
        send_alert(f"🛡️ Flare Mode Active: Penalty for '{reason}' suppressed.")
        return
    data["total_credits"] -= points
    data["history"].append({"timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"), "task": f"PENALTY: {reason}", "points": -points})
    save_data(data)
    send_alert(f"⚠️ PENALTY: {reason} (-{points} pts)")

def get_main_keyboard():
    return {
        "keyboard": [
            [{"text": "💊 Meds"}, {"text": "📊 Vitals"}],
            [{"text": "🥤 Electrolytes"}, {"text": "🚨 Flare Mode"}],
            [{"text": "📈 Status"}, {"text": "🏁 Milestones"}],
            [{"text": "✏️ Custom"}, {"text": "🛠️ Fix Last"}, {"text": "📤 Export"}] # The Power Tools
        ],
        "resize_keyboard": True,
        "one_time_keyboard": False
    }

def send_alert_with_menu(message):
    # Sends a message AND brings up the buttons
    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    payload = {
        "chat_id": CHAT_ID,
        "text": message,
        "reply_markup": json.dumps(get_main_keyboard()),
        "parse_mode": "Markdown"
    }
    requests.post(url, json=payload)

print("✅ Logic Engine Online.")

# --- CELL 4: THE VISION BRIDGE ---
def get_latest_photo():
    url = f"https://api.telegram.org/bot{TOKEN}/getUpdates"
    res = requests.get(url).json()
    if not res.get("result"): return None
    for upd in reversed(res["result"]):
        if "message" in upd and "photo" in upd["message"]:
            f_id = upd["message"]["photo"][-1]["file_id"]
            f_info = requests.get(f"https://api.telegram.org/bot{TOKEN}/getFile?file_id={f_id}").json()
            f_path = f_info["result"]["file_path"]
            img = requests.get(f"https://api.telegram.org/bot{TOKEN}/file/bot{TOKEN}/{f_path}").content
            with open("capture.jpg", 'wb') as f: f.write(img)
            return "capture.jpg"
    return None

def ocr_vitals(img_path):
    img = cv2.imread(img_path)
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    # MASKING FOR GREEN (HR)
    mask = cv2.inRange(hsv, np.array([35, 50, 50]), np.array([85, 255, 255]))
    text = pytesseract.image_to_string(mask, config='--psm 7 digits')
    return text.strip()

print("✅ Vision Systems Ready.")

# --- CELL 5: THE RUNTIME COMMANDER ---

# 1. DAILY BOOT CHECK (Automated)
today = datetime.now().strftime("%Y-%m-%d")
history = load_data()['history']
if not any(e['task'] == "System Init" and e['timestamp'].startswith(today) for e in history):
    add_credits("System Init", 50)

# 2. ENHANCED DASHBOARD MENU
print("\n" + "="*40)
print("   🧠 MIRACLE BRIDGE COMMAND CENTER v1.4")
print("="*40)
print(" [LOGGING]      [SYSTEM]        [DATA]")
print(" meds           flare           view_vitals")
print(" vitals         milestones      fix")
print(" auto           status          custom")
print("="*40)

cmd = input("Awaiting command: ").lower().strip()

# 3. COMMAND LOGIC
if cmd == "meds":
    now = datetime.now().strftime("%H:%M")
    data = load_data()

    # Find the closest scheduled med
    # (This is simplified: it looks for the med you should take around now)
    current_hour = datetime.now().hour

    # Logic: If you take it within 1 hour of the scheduled time
    found = False
    for med_time, med_name in MED_SCHEDULE.items():
        sched_hour = int(med_time.split(":")[0])
        if abs(current_hour - sched_hour) <= 1:
            add_credits(f"On-Time Meds: {med_name}", 30) # Higher points for schedule!
            found = True
            break

    if not found:
        # If you take it way off schedule, you still get points, but fewer.
        add_credits("Off-Schedule Rescue Meds", 15)


elif cmd == "vitals":
  add_credits("Manual Vitals", 10)

elif cmd == "flare":
    data = load_data()
    status = not data.get("flare_mode", False)
    data["flare_mode"] = status
    save_data(data)
    send_alert(f"{'🚨 FLARE ON' if status else '🟢 NORMAL MODE'}")

elif cmd == "milestones":
    # (Insert the milestones logic we just wrote)
    balance = load_data()['total_credits']
    levels = [(250, "L1: Boot"), (750, "L2: Stability"), (1500, "L3: Specialist"), (2500, "L4: KEYBOARD")]
    print("\n--- 🏁 CHECKPOINTS ---")
    for pts, label in levels:
        status = "✅" if balance >= pts else f"🔒 {pts - balance} left"
        print(f"{label:<20} | {status}")

elif cmd == "view_vitals":
    data = load_data()
    print(f"\n{'Timestamp':<20} | {'Vital/Task'}")
    print("-" * 50)
    # We filter for anything that looks like a vital log
    for entry in data['history'][-10:]: # Show last 10 entries
        if any(x in entry['task'] for x in ["HR:", "Vitals", "CORRECTED"]):
            print(f"{entry['timestamp']:<20} | {entry['task']}")

elif cmd == "auto":
    print("📡 Listening for Telegram photo... (Send it now!)")
    while True:
        photo_path = get_latest_photo()
        if photo_path:
            print("📸 Image detected. Processing...")
            val = ocr_vitals(photo_path)
            add_credits(f"Auto-Log (HR: {val})", 30)
            break
        time.sleep(5)

elif cmd == "fix":
    data = load_data()
    if not data['history']:
        print("❌ No history found to correct.")
    else:
        last_entry = data['history'][-1]
        print(f"⚠️ Last Log was: {last_entry['task']}")
        new_val = input("Enter correct value: ")

        # We update the description so you have an audit trail
        data['history'][-1]['task'] = f"CORRECTED: {new_val}"
        save_data(data)
        send_alert(f"🔧 Correction complete. Log now reads: {new_val}")

elif cmd == "status":
    data = load_data()
    mode = "🚨 FLARE" if data.get("flare_mode") else "🟢 NORMAL"
    print(f"Current Balance: {data['total_credits']} pts")
    send_alert(f"STATUS CHECK: {mode}\nBalance: {data['total_credits']} / {TARGET_GOAL}")

elif cmd == "custom":
    task = input("What did you achieve? ")
    pts_input = input("Points earned (numbers only)? ")

    try:
        pts = int(pts_input)
        add_credits(task, pts)
    except ValueError:
        print(f"❌ '{pts_input}' is not a number! Use digits only (e.g. 50).")
        print("Command aborted. Please try again.")

else:
    print("❓ Command not recognized. Try again.")

# --- CELL 6: THE COMMANDER & GUARDIAN (v1.7 - REZNOR EDITION) ---
import time
import pytz
from datetime import datetime

# 1. INITIAL SYNC
print("🛡️ System Online: Listening for Telegram Commands & Photos...")
cdmx_tz = pytz.timezone('America/Mexico_City')

# Force-clear the buffer so we don't process old messages
requests.get(f"https://api.telegram.org/bot{TOKEN}/getUpdates?offset=-1")

while True:
    try:
        # 2. TIME & DATA REFRESH
        now_cdmx = datetime.now(cdmx_tz)
        now_time = now_cdmx.strftime("%H:%M")
        today = now_cdmx.strftime("%Y-%m-%d")
        data = load_data()

        # 3. READ TELEGRAM MESSAGES
        url = f"https://api.telegram.org/bot{TOKEN}/getUpdates"
        res = requests.get(url).json()


        if res.get("result"):
            for update in res["result"]:
                update_id = update["update_id"]
                last_processed = data.get("last_update_id", 0)

                if update_id > last_processed:
                    msg = update.get("message", {})
                    raw_text = msg.get("text", "").lower()
                    print(f"📥 Received: {raw_text}") # Debug: See what the bot sees in Colab

                    # --- COMMAND ROUTING ---
                    if "meds" in raw_text:
                      add_credits("Medication Protocol", 30)
                      send_alert_with_menu("💊 Meds Logged! (+30 pts)")

                    elif "vitals" in raw_text:
                      add_credits("Manual Vitals", 10)
                      send_alert_with_menu("📊 Vitals Logged! Data synced to archive! (+10 pts)")

                    elif "electrolytes" in raw_text:
                      add_credits("Hydration/Electrolytes", 15)
                      send_alert_with_menu("🥤 Electrolytes Logged. Stay hydrated (+15 pts)")

                    elif "flare" in raw_text or text == "🚨 flare mode":
                        status = not data.get("flare_mode", False)
                        # Ensure set_flare_mode(status) is in Cell 3!
                        data["flare_mode"] = status
                        save_data(data)
                        msg = "🚨 EMERGENCY PROTOCOL: Flare Mode Active. 2X Points!" if status else "🟢 SYSTEM STABILIZED: Normal Mode."
                        send_alert_with_menu(msg)

                    elif "snooze" in raw_text or text == "💤 snooze 15m":
                        snooze_system(15)
                        send_alert_with_menu("💤 System Snoozed for {minutes}m. Rest up, Architect.")

                    if "milestones" in raw_text:
                      bal = data['total_credits']
                      left = 250 - bal if bal < 250 else "UNLOCKED 🔓"
                      send_alert_with_menu(f"🏁 **MILESTONE TRACKER**\nL1 (250): {'✅'if bal >= 250 else f'🔒 {left} pts left'}")

                    elif "custom" in raw_text:
                      add_credits("Custom Architect Task", 20)
                      send_alert_with_menu("✏️ **CUSTOM LOG**: +20 pts added to the mainframe!")

                    elif "status" in raw_text:
                       mode = "🚨 FLARE" if data.get("flare_mode") else "🟢 NORMAL"
                       send_alert_with_menu(f"📈 **STATUS**: {mode} | {data['total_credits']} pts")

                    elif "fix" in raw_text:
                      data = load_data()
                      if data['history']:
                        removed = data['history'].pop() # Remove the last entry
                        data['total_credits'] -= removed['points']
                        save_data(data)
                        send_alert_with_menu(f"🛠️ **REDACTED**: Removed '{removed['task']}' and {removed['points']} pts.")
                      else: send_alert_with_menu("❌ Nothing to fix! History is empty.")

                    elif "export" in text or text == "📤 export":
                        if data['total_credits'] >= 250:
                            # Ensure export_to_csv() is in Cell 3!
                            csv_path = export_to_csv()
                            send_alert_with_menu(f"📤 **REPORT GENERATED**: Check your Google Drive for the CSV!")
                        else:
                            send_alert_with_menu(f"🔒 Level 1 Required. {250 - data['total_credits']} pts left.")


                    # 4. PHOTO PROCESSING
                    elif "photo" in msg:
                        f_id = msg["photo"][-1]["file_id"]
                        f_info = requests.get(f"https://api.telegram.org/bot{TOKEN}/getFile?file_id={f_id}").json()
                        f_path = f_info["result"]["file_path"]
                        img_bytes = requests.get(f"https://api.telegram.org/bot{TOKEN}/file/bot{TOKEN}/{f_path}").content
                        with open("capture.jpg", 'wb') as f: f.write(img_bytes)
                        val = ocr_vitals("capture.jpg")
                        add_credits(f"Auto-Log (HR: {val})", 30)
                        send_alert_with_menu(f"📸 **AUTO-LOG SUCCESS**: Heart Rate {val} recorded! (+30 pts)")

                    # Update processed marker
                    data["last_update_id"] = update_id
                    save_data(data)

        # 5. SCHEDULED ALERTS (Every minute check)
        if time.time() > data.get("snooze_until", 0):
            for m_t, m_n in MED_SCHEDULE.items():
                if now_time == m_t:
                    # Check if already taken today
                    taken = any(m_n in e['task'] and e['timestamp'].startswith(today) for e in data['history'])
                    if not taken:
                        send_alert_with_menu(f"🔔 **TIME SENSITIVE**: {m_n} due! (Window: 5m)")
                        time.sleep(61) # Don't spam same minute

    except Exception as e:
        # Uncomment for debugging: print(f"Guardian error: {e}")
        pass

    time.sleep(3) #
